import "./globals.css";
import Footer from "./components/UI/footer";
import Header from "./components/UI/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-cyan-900 dark:bg-cyan-200 text-cyan-200 dark:text-cyan-800">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
